name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Nuxt.js
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dev dependencies
        run: |
          npm install
          npm list --depth=0
        continue-on-error: true
      - name: Run build
        run: DEPLOY_ENV=GH_PAGES npm run build && DEPLOY_ENV=GH_PAGES npm run export
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist