name: lint

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: ESLint & Prettier & StyleLint
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        run: |
          npm install 
          npm list --depth=0
        continue-on-error: true
      - name: Run lint
        run: npm run lint